project_id = "emnobhffpmhptfnrzitr"

[functions.view-profile]
verify_jwt = false

[functions.hh-import]
verify_jwt = false

[functions.profile-api]
verify_jwt = false

[functions.send-interview-email]
verify_jwt = false